# Generated by Django 2.2 on 2022-04-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
